### ISSUE TITLE
Inimigos com inteligência artificial

### ISSUE THREAD

**Issue by eduardovra** [fabiokr/Bomberman#20]
Ver se o unity tem suporte pra fazer isso de uma maneira fácil.

**Comment by eduardovra** [comment]
Começar instanciando um segundo bomberman com inteligência artificial para permitir um modo versus com um jogador.

**Comment by eduardovra** [comment]
Vamos fazer mesmo isso ?
Acho que não precisa né

**Comment by fabiokr** [comment]
Agree :D
