### ISSUE TITLE
Bomberman deve morrer quando atingido por bomba

### ISSUE THREAD

**Issue by eduardovra** [fabiokr/Bomberman#54]

**Comment by fabiokr** [comment]
Isso é um bug, estava funcionando mas parou de funcionar por algum motivo.

**Comment by eduardovra** [comment]
Pode ter sido culpa minha, quando eu importei o novo modelo do bomberman tive que recriar o prefab. De certo faltou ativar/desativar alguma opção

**Comment by fabiokr** [comment]
Corrig a posição do capsule collider aqui 6e65c79789dd2246a21552e8b596ad38edda539c, e resolveu o problema.
