### ISSUE TITLE
Bug ao pegar item

### ISSUE THREAD

**Issue by fabiokr** [fabiokr/Bomberman#59]
As vezes quando tento pegar um item chegando nele de lado, o bomberman para na frente do item por um tempo, como se tivesse parado em um colisor.

**Comment by eduardovra** [comment]
Será que não pode ser um delay que da as vezes no Destroy ? Se tivesse uma forma de configurar o item como não-fisico era melhor.

**Comment by fabiokr** [comment]
O estranho eh q se for pegar o item na vertical nao consigo reproduzir o
problema.

**Comment by eduardovra** [comment]
Hum.. Eu tive que reduzir o tamanho do colisor do item, porque as vezes o item tava sendo pego atraves dos blocos. Acho que aconteceu porque a animação faz o item ficar se movendo. Talvez seja por isso.
Da pra pensar em alguma forma de deixar o colisor parado.
