### ISSUE TITLE
Explosão está afetando o Bomberman

### ISSUE THREAD

**Issue by fabiokr** [fabiokr/Bomberman#8]
Quando uma bomba explode, ela está empurrando o bomberman.

**Comment by eduardovra** [comment]
Também percebi isso. Talvez não seja problema, porque se a explosão atinge ele, ele morre. Pensei que poderia setar o is kinematic pra 0 e rolar uma animação.
Só tem que confirmar se a explosão não esta atravessando paredes.

**Comment by fabiokr** [comment]
Abri um PR que explode blocos mais distantes, e parece que a explosao também está afetando o impulso deles. Será que esse efeito de explosão aplica fisica de explosão também? Se sim, deveríamos deixar só o efeito visual.
